on: [push]

jobs:
  extractor:
    runs-on: ubuntu-latest
    name: tag extractor
    steps:
      - uses: actions/checkout@v3

      - name: Get git tag
        id: extractor
        uses: solte-go/git-tag-output-action@master

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The tag is ${{ steps.extractor.outputs.tag }}"
