on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: extractor
        uses: solte-go/git-tag-output-action@master

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.extractor.outputs.tag }}"
